config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :professors do
    resources :professor_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :courses do
    resources :course_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :students

  post '/courses/:id/students', to: 'courses#add_student'
  delete '/courses/:id/students/:student_id', to: 'courses#delete_student'
  post '/courses/:id/professors', to: 'courses#add_professor'
  delete '/courses/:id/professors/:professor_id', to: 'courses#delete_professor'
  post '/students/:id/courses', to: 'students#add_course'
  delete '/students/:id/courses/:course_id', to: 'students#delete_course'
  post '/professors/:id/courses', to: 'professors#add_course'
  delete '/professors/:id/courses/:course_id', to: 'professors#delete_course'
end

app/models/student.rb
class Student < ApplicationRecord
  validates_presence_of :first_name, :last_name
  has_many :courses_students, dependent: :destroy
  has_many :courses, through: :courses_students

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  before_action :set_student, only: [:show, :edit, :update, :destroy, :add_course, :delete_course]

  # GET /students
  # GET /students.json
  def index
    @students = Student.all
  end

  # GET /students/1
  # GET /students/1.json
  def show
    @courses = Course.all
  end

  # GET /students/new
  def new
    @student = Student.new
  end

  # GET /students/1/edit
  def edit
  end

  # POST /students
  # POST /students.json
  def create
    @student = Student.new(student_params)

    respond_to do |format|
      if @student.save
        format.html { redirect_to @student, notice: 'Student was successfully created.' }
        format.json { render :show, status: :created, location: @student }
      else
        format.html { render :new }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /students/1
  # PATCH/PUT /students/1.json
  def update
    respond_to do |format|
      if @student.update(student_params)
        format.html { redirect_to @student, notice: 'Student was successfully updated.' }
        format.json { render :show, status: :ok, location: @student }
      else
        format.html { render :edit }
        format.json { render json: @student.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /students/1
  # DELETE /students/1.json
  def destroy
    @student.destroy
    respond_to do |format|
      format.html { redirect_to students_url, notice: 'Student was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_course
    if params[:course_id].present?
      @course = Course.find(params[:course_id])
      @student.courses << @course unless @student.courses.include? @course
    end
    redirect_to "/students/#{@student.id}"
  end

  def delete_course
    @course = Course.find(params[:course_id])
    @student.courses.delete(@course)
    redirect_to "/students/#{@student.id}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_student
    @student = Student.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def student_params
    params.require(:student).permit(:first_name, :last_name)
  end
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/students/_form.html.erb
<%= form_with(model: student, local: true) do |form| %>
  <% if student.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :student_first_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :student_last_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Editing Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Students</h1>

<table class="table table-light">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Enrolled</th>
        </tr>
    </thead>
    <tbody>
        <% @students.each do |student| %>
        <tr>
        <td><%= link_to student.full_name, "/students/#{student.id}" %></td>
        <td><%= pluralize student.courses.size, 'course' %></td>
    </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>New Student</h1>

<%= render 'form', student: @student %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @student.full_name %></h1>

<h2>Courses:</h2>
<% if @student.courses.empty? %>
  <p>Not enrolled in any courses yet...</p>
<% else %>
  <ul>
    <% @student.courses.each do |course| %>
      <li><%= link_to course.full_title, "/courses/#{course.id}" %> | <%= link_to 'Drop', "/students/#{@student.id}/courses/#{course.id}", method: :delete %></li>
    <% end %>
  </ul>
<% end %>

<strong>Add a course:</strong>
<%= form_with url: "/students/#{@student.id}/courses" do |form| %>
  <%= form.collection_select :course_id, @courses, :id, :full_title, prompt: true %>
  <%= form.submit 'Add Course' %>
<% end %>

<br>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Destroy', "/students/#{@student.id}", method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', students_path %>