config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :professors do
    resources :professor_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :courses do
    resources :course_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :students

  post '/courses/:id/students', to: 'courses#add_student'
  delete '/courses/:id/students/:student_id', to: 'courses#delete_student'
  post '/courses/:id/professors', to: 'courses#add_professor'
  delete '/courses/:id/professors/:professor_id', to: 'courses#delete_professor'
  post '/students/:id/courses', to: 'students#add_course'
  delete '/students/:id/courses/:course_id', to: 'students#delete_course'
  post '/professors/:id/courses', to: 'professors#add_course'
  delete '/professors/:id/courses/:course_id', to: 'professors#delete_course'
end

app/controllers/course_reviews_controller.rb
class CourseReviewsController < ApplicationController
  before_action :set_course
  before_action :set_course_review, except: [:create]

  # POST /course_reviews
  # POST /course_reviews.json
  def create
    @course_review = @course.course_reviews.create(course_review_params)
    redirect_to "/courses/#{@course.id}"
  end

  # GET /course_reviews/1/edit
  def edit
  end

  # PATCH/PUT /course_reviews/1
  # PATCH/PUT /course_reviews/1.json
  def update
    if @course_review.update(course_review_params)
      redirect_to "/courses/#{@course.id}"
    else
      render :edit
    end
  end

  # DELETE /course_reviews/1
  # DELETE /course_reviews/1.json
  def destroy
    @course_review.destroy
    redirect_to "/courses/#{@course.id}"
  end

  private

  def set_course
    @course = Course.find(params[:course_id])
  end

  def set_course_review
    @course_review = CourseReview.find(params[:id])
  end

  def course_review_params
    params.require(:course_review).permit(:content)
  end
end

app/helpers/course_reviews_helper.rb
module CourseReviewsHelper
end

app/views/course_reviews/_form.html.erb
<%= form_with(model: course_review, local: true) do |form| %>
  <% if course_review.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course_review.errors.count, "error") %> prohibited this course_review from being saved:</h2>

      <ul>
      <% course_review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :course_review_content %>
  </div>

  <div class="field">
    <%= form.label :course_id %>
    <%= form.text_field :course_id, id: :course_review_course_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/course_reviews/edit.html.erb
<h1>Editing Course Review</h1>

<%= render 'form', course_review: @course_review %>

<%= link_to 'Show', @course_review %> |
<%= link_to 'Back', course_reviews_path %>

app/views/course_reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Course Reviews</h1>

<table>
  <thead>
    <tr>
      <th>Content</th>
      <th>Course</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @course_reviews.each do |course_review| %>
      <tr>
        <td><%= course_review.content %></td>
        <td><%= course_review.course %></td>
        <td><%= link_to 'Show', course_review %></td>
        <td><%= link_to 'Edit', edit_course_review_path(course_review) %></td>
        <td><%= link_to 'Destroy', course_review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Course Review', new_course_review_path %>

app/views/course_reviews/new.html.erb
<h1>New Course Review</h1>

<%= render 'form', course_review: @course_review %>

<%= link_to 'Back', course_reviews_path %>

app/views/course_reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @course_review.content %>
</p>

<p>
  <strong>Course:</strong>
  <%= @course_review.course %>
</p>

<%= link_to 'Edit', edit_course_review_path(@course_review) %> |
<%= link_to 'Back', course_reviews_path %>