config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :professors do
    resources :professor_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :courses do
    resources :course_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :students

  post '/courses/:id/students', to: 'courses#add_student'
  delete '/courses/:id/students/:student_id', to: 'courses#delete_student'
  post '/courses/:id/professors', to: 'courses#add_professor'
  delete '/courses/:id/professors/:professor_id', to: 'courses#delete_professor'
  post '/students/:id/courses', to: 'students#add_course'
  delete '/students/:id/courses/:course_id', to: 'students#delete_course'
  post '/professors/:id/courses', to: 'professors#add_course'
  delete '/professors/:id/courses/:course_id', to: 'professors#delete_course'
end

app/models/professor.rb
class Professor < ApplicationRecord
  validates_presence_of :first_name, :last_name
  has_many :courses_professors, dependent: :destroy
  has_many :courses, through: :courses_professors

  has_many :professor_reviews, dependent: :destroy

  def full_name
    "#{first_name} #{last_name}"
  end
end

app/controllers/professors_controller.rb
class ProfessorsController < ApplicationController
  before_action :set_professor, only: [:show, :edit, :update, :destroy, :add_course, :delete_course]

  # GET /professors
  # GET /professors.json
  def index
    @professors = Professor.all
  end

  # GET /professors/1
  # GET /professors/1.json
  def show
    @courses = Course.all
  end

  # GET /professors/new
  def new
    @professor = Professor.new
  end

  # GET /professors/1/edit
  def edit
  end

  # POST /professors
  # POST /professors.json
  def create
    @professor = Professor.new(professor_params)

    respond_to do |format|
      if @professor.save
        format.html { redirect_to @professor, notice: 'Professor was successfully created.' }
        format.json { render :show, status: :created, location: @professor }
      else
        format.html { render :new }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /professors/1
  # PATCH/PUT /professors/1.json
  def update
    respond_to do |format|
      if @professor.update(professor_params)
        format.html { redirect_to @professor, notice: 'Professor was successfully updated.' }
        format.json { render :show, status: :ok, location: @professor }
      else
        format.html { render :edit }
        format.json { render json: @professor.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /professors/1
  # DELETE /professors/1.json
  def destroy
    @professor.destroy
    respond_to do |format|
      format.html { redirect_to professors_url, notice: 'Professor was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_course
    if params[:course_id].present?
      @course = Course.find(params[:course_id])
      @professor.courses << @course unless @professor.courses.include? @course
    end
    redirect_to "/professors/#{@professor.id}"
  end

  def delete_course
    @course = Course.find(params[:course_id])
    @professor.courses.delete(@course)
    redirect_to "/professors/#{@professor.id}"
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_professor
    @professor = Professor.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def professor_params
    params.require(:professor).permit(:first_name, :last_name)
  end
end

app/helpers/professors_helper.rb
module ProfessorsHelper
end

app/views/professors/_form.html.erb
<%= form_with(model: professor, local: true) do |form| %>
  <% if professor.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(professor.errors.count, "error") %> prohibited this professor from being saved:</h2>

      <ul>
      <% professor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :first_name %>
    <%= form.text_field :first_name, id: :professor_first_name, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :last_name %>
    <%= form.text_field :last_name, id: :professor_last_name, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/professors/edit.html.erb
<h1>Editing Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Show', @professor %> |
<%= link_to 'Back', professors_path %>

app/views/professors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Professors</h1>

<table class="table table-light">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Name</th>
            <th scope="col">Teaching</th>
            <th scope="col">Review</th>
        </tr>
    </thead>
    <tbody>
        <% @professors.each do |professor| %>
        <tr>
        <td><%= link_to professor.full_name, "/professors/#{professor.id}" %></td>
        <td><%= pluralize professor.courses.size, 'course' %></td>
        <td><%= pluralize professor.professor_reviews.size, 'review' %></td>
    </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Professor', new_professor_path %>

app/views/professors/new.html.erb
<h1>New Professor</h1>

<%= render 'form', professor: @professor %>

<%= link_to 'Back', professors_path %>

app/views/professors/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @professor.full_name %></h1>

<br>

<h3>Courses Taught:</h3>
    <% if @professor.courses.empty? %>
      <p>Not teaching any courses yet...</p>
    <% else %>
      <ul>
        <% @professor.courses.each do |course| %>
          <li><%= link_to course.full_title, "/courses/#{course.id}" %> | <%= link_to 'Quit', "/professors/#{@professor.id}/courses/#{course.id}", method: :delete %></li>
        <% end %>
      </ul>
<% end %>

<br>

<strong>Assign a course:</strong>
    <%= form_with url: "/professors/#{@professor.id}/courses" do |form| %>
    <%= form.collection_select :course_id, @courses, :id, :full_title, prompt: true %>
    <%= form.submit 'Add Course' %>
<% end %>

<br>

<h2>Reviews:</h2>
<% if @professor.professor_reviews.empty? %>
  <p>No reviews yet...</p>
<% else %>
  <ul>
    <% @professor.professor_reviews.each do |review| %>
      <li><%= review.content %> | <%= link_to 'Edit', "/professors/#{@professor.id}/professor_reviews/#{review.id}/edit" %> | <%= link_to 'Destroy', "/professors/#{@professor.id}/professor_reviews/#{review.id}", method: :delete %></li>
    <% end %>
  </ul>
<% end %>

<h3>Add a review:</h3>
<%= form_with url: "/professors/#{@professor.id}/professor_reviews" do |form| %>
  <%= form.text_area 'professor_review[content]' %><br>
  <%= form.submit 'Add Review' %>
<% end %>


<br>

<%= link_to 'Edit', edit_professor_path(@professor) %> |
<%= link_to 'Destroy', "/professors/#{@professor.id}", method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', professors_path %>