config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'
  resources :professors do
    resources :professor_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :courses do
    resources :course_reviews, only: [:edit, :create, :update, :destroy]
  end
  resources :students

  post '/courses/:id/students', to: 'courses#add_student'
  delete '/courses/:id/students/:student_id', to: 'courses#delete_student'
  post '/courses/:id/professors', to: 'courses#add_professor'
  delete '/courses/:id/professors/:professor_id', to: 'courses#delete_professor'
  post '/students/:id/courses', to: 'students#add_course'
  delete '/students/:id/courses/:course_id', to: 'students#delete_course'
  post '/professors/:id/courses', to: 'professors#add_course'
  delete '/professors/:id/courses/:course_id', to: 'professors#delete_course'
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy, :add_student, :delete_student, :add_professor, :delete_professor]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
    @students = Student.all
    @professors = Professor.all
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def add_student
    if params[:student_id].present?
      @student = Student.find(params[:student_id])
      @course.students << @student unless @course.students.include? @student
    end
    redirect_to "/courses/#{@course.id}"
  end

  def delete_student
    @student = Student.find(params[:student_id])
    @course.students.delete(@student)
    redirect_to "/courses/#{@course.id}"
  end

  def add_professor
    if params[:professor_id].present?
      @professor = Professor.find(params[:professor_id])
      @course.professors << @professor unless @course.professors.include? @professor
    end
    redirect_to "/courses/#{@course.id}"
  end

  def delete_professor
    @professor = Professor.find(params[:professor_id])
    @course.professors.delete(@professor)
    redirect_to "/courses/#{@course.id}"
  end

  private

  def set_course
    @course = Course.find(params[:id])
  end

  def course_params
    params.require(:course).permit(:number, :title, :description)
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
      <% course.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= form.label :number %>
    <%= form.text_field :number, id: :course_number, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :course_title, class: 'form-control' %>
  </div>

  <div class="field form-group">
    <%= form.label :description %>
    <%= form.text_area :description, id: :course_description, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit class: 'btn btn-dark' %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Courses</h1>

<table class="table table-light">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Full Title</th>
            <th scope="col">Class Size</th>
            <th scope="col">Review</th>
        </tr>
    </thead>
    <tbody>
        <% @courses.each do |course| %>
        <tr>
        <td><%= link_to course.full_title, "/courses/#{course.id}" %></td>
        <td><%= pluralize course.students.size, 'student' %> enrolled</td>
        <td><%= pluralize course.course_reviews.size, 'review' %></td>
    </tr>
        <% end %>
    </tbody>
</table>

<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @course.title %> <%= @course.number %></h1><h1><%= @course.description %></h1>

<br>

<div class="row">
  <div class="col">
    <h2>Professors:</h2>
    <% @course.professors.each do |professor| %>
      <li><%= link_to professor.full_name, "/professors/#{professor.id}" %> | <%= link_to 'Unassign', "/courses/#{@course.id}/professors/#{professor.id}", method: :delete %></li>
    <% end %>
  </div>

  <div class="col">
    <h2>Students:</h2>
    <% @course.students.each do |student| %>
      <li><%= link_to student.full_name, "/students/#{student.id}" %> | <%= link_to 'Unenroll', "/courses/#{@course.id}/students/#{student.id}", method: :delete %></li>
    <% end %>
  </div>
</div>

<br>

<div class="row">
<div class="col">
  <strong>Assign a professor:</strong>
  <%= form_with url: "/courses/#{@course.id}/professors" do |form| %>
  <%= form.collection_select :professor_id, @professors, :id, :full_name, prompt: true %>
  <%= form.submit 'Add Professor' %>
<% end %>
</div>

<div class="col">
  <strong>Add a student:</strong>
  <%= form_with url: "/courses/#{@course.id}/students" do |form| %>
  <%= form.collection_select :student_id, @students, :id, :full_name, prompt: true %>
  <%= form.submit 'Add Student' %>
<% end %>
</div>
</div>

<br>

<h2>Reviews:</h2>
<% if @course.course_reviews.empty? %>
  <p>No reviews yet...</p>
<% else %>
  <ul>
    <% @course.course_reviews.each do |review| %>
      <li><%= review.content %> | <%= link_to 'Edit', "/courses/#{@course.id}/course_reviews/#{review.id}/edit" %> | <%= link_to 'Destroy', "/courses/#{@course.id}/course_reviews/#{review.id}", method: :delete %></li>
    <% end %>
  </ul>
<% end %>

<br>

<h3>Add a review:</h3>
<%= form_with url: "/courses/#{@course.id}/course_reviews" do |form| %>
  <%= form.text_area 'course_review[content]' %><br>
  <%= form.submit 'Add Review' %>
<% end %>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Destroy', "/courses/#{@course.id}", method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', courses_path %>